# Site settings
name: Stat 585 at ISU
title: Data Technologies for Statistics
email: hofmann@iastate.edu
description: Not all data lives in nice, clean spreadsheets, not all data fits in a computer's main memory.
# Build settings
markdown: kramdown
url: http://localhost:4000
markdown: kramdown
navigation:
- text: Home
  url: /index.html
- text: Schedule
  url: /schedule.html
- text: Labs
  url: /labs.html
- text: Blog
  url: /blog
  layout:
    - post
    - blog
- text: Final Projects
  url: /projects.html
- text: Final Presentations
  url: /presentations.html
collections:
  blog:
    output: true
    permalink: /blog-2022/:path
  topics:
    output: true
    permalink: /blog-2022/:path/

theme: jekyll-theme-minimal
